// @ts-ignore
import url_13_4 from './typo3-13.4.zip?url';

/**
 * This file was auto generated by packages/playground/typo3-builds/build/build.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export function getTYPO3ModuleDetails(TYPO3Version: string = '13.4'): {
	size: number;
	url: string;
} {
	switch (TYPO3Version) {
		case '13.4':
			/** @ts-ignore */
			return {
				size: 24580797,
				url: url_13_4,
			};
	}
	throw new Error('Unsupported TYPO3 module: ' + TYPO3Version);
}
