/**
 * This file lives outside of the `src/wordpress` directory on
 * purpose.
 *
 * `src/wordpress` hosts autogenerated code and is added to eslint
 * and NX ignore lists. However, this test file is written by hand
 * and should still be linted and picked up by the test runner.
 */

import { getTYPO3ModuleDetails } from './typo3/get-typo3-module-details';

describe('getTYPO3ModuleDetails()', () => {
	it('should return a data loader module', async () => {
		const module = getTYPO3ModuleDetails();
		expect(module.url).toMatch(/\/wp-\d.\d.zip$/);
	});
});
